### PR TITLE
ordering recipes

### PR DESCRIPTION
**Pull request by vfyjxf**
make recipes  in order

### CODE REVIEW

**Comment by brachy84** [comment]
`TreeMap` :skull:

**Comment by brachy84** [comment]
I've heard of several issues related to `TreeMap`. I would use `Object2ObjectLinkedOpenHashMap`.

**Comment by vfyjxf** [comment]
> I've heard of several issues related to `TreeMap`. I would use `Object2ObjectLinkedOpenHashMap`.

Humm, I don't know much about TreeMap, I should listen to you.

**Comment by vfyjxf** [comment]
> I've heard of several issues related to `TreeMap`. I would use `Object2ObjectLinkedOpenHashMap`.

Sorry, I forgot that the order should be based on the recipe id, so I need a Map that can sort by key.

**Comment by KorewaLidesu** [comment]
Just generate num or something on recipe creating or something to indicate??

**Comment by vfyjxf** [comment]
> Just generate num or something on recipe creating or something to indicate??

merely guarantees the ordering of the recipes at jei and retrieval while the set of recipes remains unchanged.
It, doesn't obviously offer a number or anything else.
Perhaps I should actively do a sort after the recipes have all been added to avoid performance issues caused by too much sorting.

**Comment by brachy84** [comment]
You can try `Object2ObjectAVLTreeMap`. It accepts a key comparator.

**Pull request merged**
