### PR TITLE
predicate condition backport

### PR DESCRIPTION
**Pull request by vfyjxf**

### CODE REVIEW

**Comment by vfyjxf** [comment]
Examples:
```js 
recipeMap.start()
    .duration(100)
    .inputItems(<ore:ingotIron>)
    .outputItems(<minecraft:gold_ingot>)
    .predicate(function (logic as RecipeLogic, recipe as Recipe) as bool {
        return logic.fuelMaxTime >= 10;
    } as IPredicateFunction,"Hello World(Fuel Time >= 10)")
    .buildAndRegister();
```

**Comment by friendlyhj** [comment]
IPredicateFunction class doesn't exist in your PR. 🤔

**Comment by vfyjxf** [comment]
> IPredicateFunction class doesn't exist in your PR. 🤔
I don't know what happened, but now it exists.

**Comment by Rongmario** [comment]
@vfyjxf @friendlyhj is this PR ready?

**Comment by vfyjxf** [comment]
> @vfyjxf @friendlyhj is this PR ready?

I think it should be fine (maybe)

**Pull request merged**
